server:
  port: 8081

spring:
  application:
    name: usermanagement
  datasource:
    url: jdbc:mysql://localhost:3307/user_management3
    username: root
    password: root
  servlet:
    multipart:
      enabled: true


